spring.application.name=api-gateway

server.port=8080

# =====================================================
# Eureka
# =====================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/


# =====================================================
# API Gateway Routes
# =====================================================

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**


spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/products/**


spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/orders/**


# =====================================================
# Actuator
# =====================================================

management.endpoints.web.exposure.include=health,info