spring.application.name=api-gateway

server.port=8080

# =====================================================
# Eureka
# =====================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

jwt.public-key-path=classpath:public.pem
jwt.issuer=shopsphere-user-service


# =====================================================
# API Gateway Routes
# =====================================================

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**


spring.cloud.gateway.server.webflux.routes[1].id=product-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/products/**


spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/orders/**

# Authentication
spring.cloud.gateway.server.webflux.routes[3].id=user-auth-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webflux.routes[4].id=inventory-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://inventory-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/inventory/**


# =====================================================
# Actuator
# =====================================================

management.endpoints.web.exposure.include=health,info